#!/usr/bin/env python3
"""Generate the paired 8-run NL/NLS global-max/action-delta screens."""

from __future__ import annotations

import tomllib
from itertools import product
from pathlib import Path


TASK_DIR = Path(__file__).resolve().parents[1]
SOURCE_DIR = TASK_DIR / "configs/no_leakage_config/Z_nl_cas_hl_shared"
OUTPUT_ROOT = TASK_DIR / "configs/no_leakage_config/F_nl_cas_hl_max_arch"

FAMILIES = ("NL", "NLS")
POOLS = {
    "mean": "mean",
    "tmean": "typed_mean",
}

# These were generated by the earlier four-run architecture screen. Remove
# only these known files so rerunning this generator cannot delete user work.
SUPERSEDED_VARIANTS = ("base", "delta", "resjk", "delta_resjk")


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) != 1:
        raise ValueError(
            f"Expected exactly one occurrence of {old!r}; found {text.count(old)}."
        )
    return text.replace(old, new, 1)


def source_path(
    family: str,
    pool_label: str,
    use_features: bool,
    action0_head: bool,
) -> Path:
    return SOURCE_DIR / (
        f"cas_hl_{family}_shared_{pool_label}_"
        f"f{int(use_features)}_a0h{int(action0_head)}_s0.toml"
    )


def generate_config(
    family: str,
    pool_label: str,
    use_features: bool,
    action0_head: bool,
) -> tuple[str, str]:
    path = source_path(family, pool_label, use_features, action0_head)
    source_name = tomllib.loads(path.read_text())["run"]["name"]
    name = (
        f"cas_hl_{family}_shared_gmax_delta_{pool_label}_"
        f"f{int(use_features)}_a0h{int(action0_head)}_s0"
    )
    text = path.read_text()

    text = replace_once(
        text,
        "# Shared-candidate-scorer bus14 run.\n"
        "# NL and NLS differ only in their input preprocessing.",
        "# Shared-candidate-scorer global-max/action-delta bus14 run.\n"
        "# NL and NLS differ only in their input preprocessing.",
    )
    text = replace_once(text, f'name = "{source_name}"', f'name = "{name}"')
    text = replace_once(text, f'exp_tag = "{source_name}"', f'exp_tag = "{name}"')
    text = replace_once(
        text,
        f"candidate_action_do_nothing_head = {str(action0_head).lower()}",
        f"candidate_action_do_nothing_head = {str(action0_head).lower()}\n"
        "candidate_action_delta_encoder = true\n"
        "candidate_action_delta_dim = 0",
    )
    text = replace_once(
        text,
        "gnn_layers = 2",
        "gnn_layers = 2\n"
        "gnn_residual = false\n"
        'gnn_jumping_knowledge = "none"',
    )
    text = replace_once(
        text,
        'gnn_readout_aggr = "mean"',
        'gnn_readout_aggr = "energized_max"',
    )
    return name, text


def validate_config(
    path: Path,
    *,
    family: str,
    pool_label: str,
    use_features: bool,
    action0_head: bool,
) -> None:
    config = tomllib.loads(path.read_text())
    run = config["run"]
    args = config["args"]

    if run["name"] != path.stem or args["exp_tag"] != path.stem:
        raise ValueError(f"Run identity does not match filename: {path}")
    checks = {
        "seed": args["seed"] == 0,
        "candidate pool": args["candidate_action_pool"] == POOLS[pool_label],
        "action features": args["candidate_action_use_features"] is use_features,
        "action-0 head": args["candidate_action_do_nothing_head"] is action0_head,
        "action delta": args["candidate_action_delta_encoder"] is True,
        "automatic delta dimension": args["candidate_action_delta_dim"] == 0,
        "shared graph encoder": args["share_actor_gnn"] is True,
        "shared scorer": args["share_candidate_scorer"] is True,
        "mp2": args["gnn_layers"] == 2,
        "global energized-max readout": args["gnn_readout_aggr"] == "energized_max",
        "no residual": args["gnn_residual"] is False,
        "no jumping knowledge": args["gnn_jumping_knowledge"] == "none",
        "NL scaling": family != "NL" or args["gnn_physical_scaling"] is False,
        "NLS scaling": family != "NLS" or args["gnn_physical_scaling"] is True,
        "NLS angle": family != "NLS" or args["gnn_angle_representation"] == "edge_diff",
    }
    failed = [name for name, passed in checks.items() if not passed]
    if failed:
        raise ValueError(f"Invalid generated config {path}: {', '.join(failed)}")


def remove_superseded_configs() -> None:
    for family in FAMILIES:
        output_dir = OUTPUT_ROOT / family
        for variant in SUPERSEDED_VARIANTS:
            path = output_dir / (
                f"cas_hl_{family}_shared_max_{variant}_f1_a0h0_s0.toml"
            )
            path.unlink(missing_ok=True)


def main() -> None:
    remove_superseded_configs()
    generated: list[Path] = []
    for family in FAMILIES:
        output_dir = OUTPUT_ROOT / family
        output_dir.mkdir(parents=True, exist_ok=True)
        combinations = product(POOLS, (False, True), (False, True))
        for pool_label, use_features, action0_head in combinations:
            name, text = generate_config(
                family,
                pool_label,
                use_features,
                action0_head,
            )
            path = output_dir / f"{name}.toml"
            path.write_text(text)
            validate_config(
                path,
                family=family,
                pool_label=pool_label,
                use_features=use_features,
                action0_head=action0_head,
            )
            generated.append(path)

    expected_total = len(FAMILIES) * len(POOLS) * 2 * 2
    if len(generated) != expected_total:
        raise RuntimeError(f"Expected {expected_total} configs; generated {len(generated)}.")
    for family in FAMILIES:
        count = len(list((OUTPUT_ROOT / family).glob("*.toml")))
        if count != 8:
            raise RuntimeError(f"Expected 8 {family} TOMLs; found {count}.")

    print(f"Generated and validated {len(generated)} configs:")
    for path in generated:
        print(path.relative_to(TASK_DIR))


if __name__ == "__main__":
    main()
