#!/usr/bin/env bash
set -euo pipefail

sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_bus_n0_none_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_bus_n1_physical_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_bus_n2_running_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_bus_n3_both_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_n0_none_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_n1_physical_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_n2_running_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_n3_both_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_line_n0_none_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_line_n1_physical_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_line_n2_running_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1_representation_normalization/gs_s1_hetero_line_n3_both_s0.toml
