#!/usr/bin/env bash
set -euo pipefail

sbatch job_jed.sh configs/gine_s0_s1_s2/best_09_shared_actor_gnn_light_gine_a4_no_concat_flat_critic_mlp_optcritic_s0.toml
sbatch job_jed.sh configs/gine_s0_s1_s2/best_09_shared_actor_gnn_light_gine_a4_no_concat_flat_critic_mlp_optcritic_s1.toml
sbatch job_jed.sh configs/gine_s0_s1_s2/best_09_shared_actor_gnn_light_gine_a4_no_concat_flat_critic_mlp_optcritic_s2.toml
sbatch job_jed.sh configs/gine_s0_s1_s2/best_10_shared_actor_gnn_light_gine_a4_concat_flat_critic_mlp_optcritic_s0.toml
sbatch job_jed.sh configs/gine_s0_s1_s2/best_10_shared_actor_gnn_light_gine_a4_concat_flat_critic_mlp_optcritic_s1.toml
sbatch job_jed.sh configs/gine_s0_s1_s2/best_10_shared_actor_gnn_light_gine_a4_concat_flat_critic_mlp_optcritic_s2.toml
