#!/usr/bin/env bash
set -euo pipefail

sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_gbi_la2b_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_gbi_lb2a_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_ga2b_lbi_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_ga2b_la2b_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_ga2b_lb2a_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_gb2a_lbi_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_gb2a_la2b_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage1d_heterogeneous_directions/gs_s1d_hetero_n0_none_gb2a_lb2a_s0.toml
