#!/usr/bin/env bash
set -euo pipefail

sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gine_max_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gine_max_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gine_max_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gat_max_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gat_max_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gat_max_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gat_mean_s0.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gat_mean_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/stage3_encoder_pooling/gs_s3ep_bus_n0_none_e0n0v0_gat_mean_s2.toml
