#!/usr/bin/env bash
set -euo pipefail

sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_ga2b_la2b_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_ga2b_lb2a_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_ga2b_lb2a_s3.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_ga2b_lbi_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_ga2b_lbi_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gb2a_la2b_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gb2a_la2b_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gb2a_lb2a_s3.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gb2a_lbi_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gb2a_lbi_s3.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gbi_la2b_s2.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gbi_la2b_s3.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gbi_lb2a_s1.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gbi_lb2a_s3.toml
sbatch job_jed.sh configs/gnn_graph_screening/heterogenous_message_direction/gs_hmd_hetero_n0_none_gbi_lbi_s1.toml
